name: meow_lang
description: "An AI-powered Meow Translator"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0
  persistent_bottom_nav_bar: ^6.2.1
  provider: ^6.1.2
  image_cropper: ^8.0.2
  audioplayers: ^6.5.1
  curved_navigation_bar: ^1.0.6
  sqflite: ^2.4.2
  record: ^6.1.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.2
  http: ^1.2.0
  image_picker: ^1.2.1
  fl_chart: ^1.2.0
  intl: ^0.20.2
  audio_2_spectrogram:
    path: lib/backend/audio_2_spectrogram
  tflite_flutter: 0.12.1 # Supports LiteRT binaries
  image: ^4.1.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename_app: ^1.6.5
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - models/deployed/model.tflite


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  remove_alpha_ios: true
